version: '2'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        restart: unless-stopped
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=Asia/Shanghai
            - PLEX_CLAIM=claim-p8efKfdAbSLGxytjvAwi
            - ADVERTISE_IP=http://192.168.2.11:32400/
        hostname: 192.168.2.11
        volumes:
            - /home/data/plex_data/db:/config
            - /home/data/plex_data/transcode:/transcode
            - /home/data/plex_data/media:/data
