emby:
    image: emby/embyserver
    restart: unless-stopped
    devices:
        - /dev/dri/renderD128
    ports:
        - "8096:8096"
        - "8920:8920"
    volumes:
        - /home/data/plex_data/media:/mnt/media
    environment:
        - GID=44
